apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonetews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonetews
  template:
    metadata:
      labels:
        app: lanchonetews
    spec:
      containers:
        - name: lanchonetews
          image: wstecnologia/lanchonetews:latest
          ports:
            - containerPort: 3000
          env:
            - name: WS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: WS_DB_HOST
            - name: WS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: WS_DB_USER
            - name: WS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: WS_DB_PASSWORD
            - name: WS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: WS_DB_NAME
            - name: WS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: WS_DB_PORT
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
