apiVersion: v1
kind: Service
metadata:
  name: lanchonetews
spec:
  type: NodePort
  ports:
    - port: {{ .Values.lanchonetews.service.port }}
      targetPort: 3000
      nodePort: 32000
  selector:
    app: lanchonetews
apiVersion: v1
kind: Service
metadata:
  name: lanchonetews
  labels:
    app: lanchonetews
spec:
  selector:
    app: lanchonetews
  ports:
    - protocol: TCP
      port: 80  # Porta exposta pelo serviço
      targetPort: 8080  # Porta onde o container está rodando
  type: LoadBalancer  # Pode ser ClusterIP, NodePort, ou LoadBalancer dependendo do seu ambiente
