apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  type: NodePort
  ports:
    - port: {{ .Values.adminer.service.port }}
      targetPort: 8080
      nodePort: 31080
  selector:
    app: adminer
