apiVersion: v1
kind: Service
metadata:
  name: techchallenge-webhook
  labels:
    app: techchallenge-webhook
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: techchallenge-webhook
